language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-18mode
  - rbx-19mode
before_install:
  - 'rm -rf $rvm_path/gems/*/{bin,gems}/rubygems-bundler-* $rvm_path/gems/*/bin/ruby_*_wrapper'
  - hash -r
  - 'curl -L https://get.smf.sh | sh'
  - 'export PATH=~/.sm/bin:$PATH'
  - 'sm ext install gem mpapis/sm_gem'
install: gem install tf -v '>=0.4.1'
before_script:
  - unset BUNDLE_GEMFILE
script: tf --text test/dtf/*
notifications:
  irc:
    channels:
      - "irc.freenode.org#rubygems-bundler"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change
matrix:
  include:
    - rvm: jruby-18mode
      env: 'JRUBY_OPTS="-X-C --server -J-XX:+TieredCompilation"'
      jdk: openjdk7
    - rvm: jruby-19mode
      env: 'JRUBY_OPTS="-X-C --server -J-XX:+TieredCompilation"'
      jdk: openjdk7
    - rvm: jruby-head
      env: 'JRUBY_OPTS="-X-C --server -J-XX:+TieredCompilation"'
      jdk: openjdk7
  allow_failures:
    - rvm: jruby-18mode
      env: 'JRUBY_OPTS="-X-C --server -J-XX:+TieredCompilation"'
      jdk: openjdk7
    - rvm: jruby-19mode
      env: 'JRUBY_OPTS="-X-C --server -J-XX:+TieredCompilation"'
      jdk: openjdk7
    - rvm: jruby-head
      env: 'JRUBY_OPTS="-X-C --server -J-XX:+TieredCompilation"'
      jdk: openjdk7
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: ruby-head
